FROM python:latest
FROM debian:latest
LABEL Maintainer="ststiche"

RUN apt-get -qq update && apt-get -qq -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3 \
    && conda update conda \
    && apt-get -qq -y remove curl bzip2 \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
    && conda clean --all --yes

RUN apt-get update && \
    apt-get install -y --no-install-recommends texlive-latex-recommended texlive-fonts-recommended && \
    apt-get install -y --no-install-recommends texlive-latex-extra texlive-fonts-extra texlive-lang-all && \
    rm -rf /var/lib/apt/lists/*

ENV PATH /opt/conda/bin:$PATH
WORKDIR /DeepPython/hw_2
VOLUME ["/DeepPython/hw_2"]
ADD . /DeepPython/hw_2

RUN pip install -r ./artifacts/requirements.txt && \
    pip install -r ./artifacts/requirements2.txt

CMD ["python", "medium.py"]